/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EasyAuction } from "./EasyAuction";

export { EasyAuction__factory } from "./factories/EasyAuction__factory";
